name: Continuous Integration

on: 
  pull_request:
  push:
    branches: 
      - main

jobs:
  test-and-lint:
    name: Run tests and lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run tests
        run: python -m unittest
      - name: Run lint
        run: black --check .
